model: "bert-base-cased"
accumulate_grad_batches: 1
use_amp: false # Half precision only works best with volta architectures such as V100
max_epochs: 4
learning_rate: 2e-5
adam_epsilon: 1e-8
warmup_steps: 0
batch_size: 48
max_length: 128