model: "roberta_large"
accumulate_grad_batches: 16
use_amp: false # Half precision only works best with volta architectures such as V100
max_epochs: 4
learning_rate: 2e-6
adam_epsilon: 10e-8
warmup_steps: 150
batch_size: 4
max_length: 128
