task_name: ace
train_x: "task_data/ace-train-dev/train.jsonl"
train_y: "task_data/ace-train-dev/train-labels.lst"
val_x: "task_data/ace-train-dev/dev.jsonl"
val_y: "task_data/ace-train-dev/dev-labels.lst"
formula: "context + question -> answer1|answer2|answer3|answer4"
