task_name: alphanli_halved-10_1
train_x: "task_data/alphanli-train-dev/halved_training/10_1/train.jsonl"
train_y: "task_data/alphanli-train-dev/halved_training/10_1/train-labels.lst"
val_x: "task_data/alphanli-train-dev/dev.jsonl"
val_y: "task_data/alphanli-train-dev/dev-labels.lst"
formula: "obs1 + obs2 -> hyp1|hyp2"
