task_name: alphanli
train_x: "task_data/AlphaNLI/train.jsonl"
train_y: "task_data/AlphaNLI/train-labels.lst"
val_x: "task_data/AlphaNLI/dev.jsonl"
val_y: "task_data/AlphaNLI/dev-labels.lst"
formula: "obs1 + obs2 -> hyp1|hyp2"
