task_name: alpha_incre_2
train_x: "task_data/AlphaNLI/increment_training/2/train.jsonl"
train_y: "task_data/AlphaNLI/increment_training/2/train-labels.lst"
val_x: "task_data/AlphaNLI/dev.jsonl"
val_y: "task_data/AlphaNLI/dev-labels.lst"
formula: "obs1 + obs2 -> hyp1|hyp2"
