task_name: alphanli-incre-50
train_x: "task_data/alphanli-train-dev/increment_training/50/train.jsonl"
train_y: "task_data/alphanli-train-dev/increment_training/50/train-labels.lst"
val_x: "task_data/alphanli-train-dev/dev.jsonl"
val_y: "task_data/alphanli-train-dev/dev-labels.lst"
formula: "obs1 + obs2 -> hyp1|hyp2"
