task_name: alphanli-retrieve_embed
train_x: "task_data/alphanli-train-dev/retrieve_embedding/train_20_0.jsonl"
train_y: "task_data/alphanli-train-dev/retrieve_embedding/train-labels_20_0.lst"
val_x: "task_data/alphanli-train-dev/retrieve_embedding/tim_story.jsonl"
val_y: "task_data/alphanli-train-dev/retrieve_embedding/tim_label.lst"
formula: "obs1 + obs2 -> hyp1|hyp2"