task_name: alphanli
train_x: "task_data/alphanli-train-dev/train-2.jsonl"
train_y: "task_data/alphanli-train-dev/train-2-labels.lst"
val_x: "task_data/alphanli-train-dev/internal-dev-2.jsonl"
val_y: "task_data/alphanli-train-dev/internal-dev-2-labels.lst"
formula: "obs1 + obs2 -> hyp1|hyp2"
