task_name: alphanli-retrieve_embed
train_x: "task_data/alphanli-train-dev/retrieve_embedding/train_5_3.jsonl"
train_y: "task_data/alphanli-train-dev/retrieve_embedding/train-labels_5_3.lst"
val_x: "task_data/alphanli-train-dev/retrieve_embedding/dev_6_id.jsonl"
val_y: "task_data/alphanli-train-dev/retrieve_embedding/dev_6_id_labels.lst"
formula: "obs1 + obs2 -> hyp1|hyp2"