task_name: alphanli-socialiqa-combined
train_x: "task_data/alphanli-socialiqa-combined-training/train.jsonl"
train_y: "task_data/alphanli-socialiqa-combined-training/train-labels.lst"
# Eval on anli
val_x: "task_data/alphanli-train-dev/dev.jsonl"
val_y: "task_data/alphanli-train-dev/dev-labels.lst"
## Eval on siqa
#val_x: "task_data/alphanli-socialiqa-combined-training/socialiqa-dev.jsonl"
#val_y: "task_data/alphanli-socialiqa-combined-training/socialiqa-dev-label.lst"
formula: "obs1 + obs2 -> hyp1|hyp2"
