task_name: alphanli_incre_30
train_x: "task_data/alphanli-train-dev/incremental_training/30/train.jsonl"
train_y: "task_data/alphanli-train-dev/incremental_training/30/train-labels.lst"
val_x: "task_data/alphanli-train-dev/dev.jsonl"
val_y: "task_data/alphanli-train-dev/dev-labels.lst"
formula: "obs1 + obs2 -> hyp1|hyp2"
