task_name: alphanli_dummy
train_x: "task_data/alphanli-train-dev/dummy/train.jsonl"
train_y: "task_data/alphanli-train-dev/dummy/train-labels.lst"
val_x: "task_data/alphanli-train-dev/dummy/dev.jsonl"
val_y: "task_data/alphanli-train-dev/dummy/dev-labels.lst"
formula: "obs1 + obs2 -> hyp1|hyp2"
