task_name: cycic_real_10
train_x: "task_data/cycic-real-10-train-dev/train.jsonl"
train_y: "task_data/cycic-real-10-train-dev/train-labels.lst"
val_x: "task_data/cycic-real-10-train-dev/dev.jsonl"
val_y: "task_data/cycic-real-10-train-dev/dev-labels.lst"
formula: "question -> answer_options"
max_epochs: 8
