task_name: cycic_mc
train_x: "task_data/cycic-mc-train-dev/train.jsonl"
train_y: "task_data/cycic-mc-train-dev/train-labels.lst"
val_x: "task_data/cycic-mc-train-dev/dev.jsonl"
val_y: "task_data/cycic-mc-train-dev/dev-labels.lst"
formula: "question -> answer_option0|answer_option1|answer_option2|answer_option3|answer_option4"
