task_name: hellaswag
train_x: "task_data/hellaswag-train-dev/train.jsonl"
train_y: "task_data/hellaswag-train-dev/train-labels.lst"
val_x: "task_data/hellaswag-train-dev/internal-dev.jsonl"
val_y: "task_data/hellaswag-train-dev/internal-dev-labels.lst"
formula: "ctx_a + ctx_b -> ending_options"
