task_name: socialiqa
train_x: "task_data/SocialIQA/train.jsonl"
train_y: "task_data/SocialIQA/train-labels.lst"
val_x: "task_data/SocialIQA/dev.jsonl"
val_y: "task_data/SocialIQA/dev-labels.lst"
formula: "context + question -> answerA|answerB|answerC"
