task_name: socialiqa
train_x: "task_data/socialiqa-train-dev/train.jsonl"
train_y: "task_data/socialiqa-train-dev/train-labels.lst"
val_x: "task_data/socialiqa-train-dev/internal-dev.jsonl"
val_y: "task_data/socialiqa-train-dev/internal-dev-labels.lst"
formula: "context + question -> answerA|answerB|answerC"
