distance_type: cosine # cosine for Cosine Distance, any integer/float for associated l_p norm distance
farthest: False
embedding_loc: outputs/embedding/OOB_bert-large-cased_ckpt_alphanli_20-bert_large-alphanli-AVG_MEAN.embed
top_N: 5
with_progress_bar: True
train_subset:
  - 0-33930
dev_subset:
  - 605
  - 763
  - 1116
  - 1273
  - 230
  - 1007
  - 1494
influential_range:
  - 16965-33930
