distance_type: cosine # cosine for Cosine Distance, any integer/float for associated l_p norm distance
farthest: False
embedding_loc: outputs/embedding/OOB_roberta-large_ckpt_alphanli_20-transformer_scratch-alphanli-AVG_MEAN.embed
top_N: 5
with_progress_bar: True
# [x, y-z] format for all subsets or range. If left empty script will treat whole file as desired range
train_subset:
  - 0-33930
dev_subset:
  - 605
  - 763
  - 1116
  - 1273
  - 230
  - 1007
  - 1494
influential_range:
  - 16965-33930
