embedding_loc: outputs/2020-06-25/20-53-53/roberta-large-alphanli-AVG_MEAN.embed
distance_type: cosine
top_N: 5
farthest: False
train_subset:
  - 0-33930
dev_subset:
  - 605
  - 763
  - 1116
  - 1273
  - 230
  - 1007
  - 1494
influential_range:
  - 16965-33930
