defaults:
  - model: roberta-large
  - task: alphanli
checkpoint_list: config/checkpoint_list/alphanli_20-transformer_scratch.lst
feature: AVG_MEAN
with_out_of_box_model: True
with_progress_bar: True
