# Default model is used when an out of box model is used to parse embedding
# Script will parse the task specified in defaults rather than task stored in ckpt files
defaults:
  - model: roberta-large
  - task: alphanli
checkpoint_list: config/checkpoint_list/alphanli_20-transformer_scratch.lst
feature: AVG_MEAN
with_out_of_box_model: True
with_progress_bar: True
