defaults:
  - model: roberta-large
  - task: physicaliqa
random_seed: 10061880
build_on_pretrained_model: False
save_best_only: True
eval_after_training: True
architecture: standard
train_data_slice: 100
hydra:
  run:
    dir: outputs