task_name: physicaliqa-10pc
model: roberta-large
accumulate_grad_batches: 16
use_amp: false
max_epochs: 4
learning_rate: 2e-6
adam_epsilon: 10e-8
warmup_steps: 150
batch_size: 4
max_length: 128
formula: "goal -> sol1|sol2"
train_x: "cache/physicaliqa-10pc-train-dev/physicaliqa-10pc-train-dev/train.jsonl"
train_y: "cache/physicaliqa-10pc-train-dev/physicaliqa-10pc-train-dev/train-labels.lst"
val_x: "cache/physicaliqa-10pc-train-dev/physicaliqa-10pc-train-dev/dev.jsonl"
val_y: "cache/physicaliqa-10pc-train-dev/physicaliqa-10pc-train-dev/dev-labels.lst"
save_path: "outputs/roberta-large-physicaliqa-10pc"

