task_name: physicaliqa-10pc
model: roberta-large
batch_size: 2
accumulate_grad_batches: 1
use_amp: false
max_epochs: 4
learning_rate: 5e-6
adam_epsilon: 1e-8
dropout: 0.5
warmup_steps: 150
max_length: 128
formula: "goal -> sol1|sol2"
train_x: "cache/physicaliqa-10pc-train-dev/physicaliqa-10pc-train-dev/train.jsonl"
train_y: "cache/physicaliqa-10pc-train-dev/physicaliqa-10pc-train-dev/train-labels.lst"
val_x: "cache/physicaliqa-10pc-train-dev/physicaliqa-10pc-train-dev/dev.jsonl"
val_y: "cache/physicaliqa-10pc-train-dev/physicaliqa-10pc-train-dev/dev-labels.lst"
save_path: "outputs/roberta-large-physicaliqa-10pc"
save_best_only: true
random_seed: 10061880
goal_inc_answers: true
embed_all_sep_mean: false