task_name: physicaliqa
model: roberta-large
batch_size: 3
accumulate_grad_batches: 8
use_amp: false
max_epochs: 6
learning_rate: 5e-6
adam_epsilon: 1e-8
dropout: 0.3
warmup_steps: 300
max_length: 128
formula: "goal -> sol1|sol2"
train_x: "cache/physicaliqa-train-dev/physicaliqa-train-dev/train.jsonl"
train_y: "cache/physicaliqa-train-dev/physicaliqa-train-dev/train-labels.lst"
val_x: "cache/physicaliqa-train-dev/physicaliqa-train-dev/dev.jsonl"
val_y: "cache/physicaliqa-train-dev/physicaliqa-train-dev/dev-labels.lst"
save_path: "outputs/roberta-large-physicaliqa"
save_best_only: true
random_seed: 10061880
goal_inc_answers: false
embed_all_sep_mean: false
