task_name: physicaliqa
model: t5-large
batch_size: 2
accumulate_grad_batches: 4
use_amp: false
max_epochs: 4
learning_rate: 5e-6
adam_epsilon: 1e-8
dropout: 0.5
warmup_steps: 150
max_length: 128
formula: "goal -> sol1|sol2"
train_x: "cache/physicaliqa-train-dev/physicaliqa-train-dev/train.jsonl"
train_y: "cache/physicaliqa-train-dev/physicaliqa-train-dev/train-labels.lst"
val_x: "cache/physicaliqa-train-dev/physicaliqa-train-dev/dev.jsonl"
val_y: "cache/physicaliqa-train-dev/physicaliqa-train-dev/dev-labels.lst"
save_path: "outputs/t5-large-physicaliqa"
save_best_only: true
random_seed: 10061880

