task_name: physicaliqa-25pc
model: t5-small
batch_size: 3
accumulate_grad_batches: 2
use_amp: false
max_epochs: 6
learning_rate: 5e-6
adam_epsilon: 1e-8
dropout: 0.3
warmup_steps: 150
max_length: 128
formula: "goal -> sol1|sol2"
train_x: "cache/physicaliqa-25pc-train-dev/physicaliqa-25pc-train-dev/train.jsonl"
train_y: "cache/physicaliqa-25pc-train-dev/physicaliqa-25pc-train-dev/train-labels.lst"
val_x: "cache/physicaliqa-25pc-train-dev/physicaliqa-25pc-train-dev/dev.jsonl"
val_y: "cache/physicaliqa-25pc-train-dev/physicaliqa-25pc-train-dev/dev-labels.lst"
save_path: "outputs/t5-small-physicaliqa-25pc"
save_best_only: true
random_seed: 10061880

